set(CMAKE_MUMPS_CREATE_SHARED_LIBRARY "<CMAKE_C_COMPILER> -shared -o <TARGET> <OBJECTS>")
set(CMAKE_MUMPS_CREATE_SHARED_MODULE "<CMAKE_C_COMPILER> <CMAKE_SHARED_LIBRARY_C_FLAGS> -o <TARGET> <OBJECTS>")
set(CMAKE_MUMPS_CREATE_STATIC_LIBRARY "")
set(CMAKE_MUMPS_COMPILE_OBJECT "<CMAKE_MUMPS_COMPILER> -object=<OBJECT> <SOURCE>")
set(CMAKE_MUMPS_LINK_EXECUTABLE "")

set(CMAKE_MUMPS_OUTPUT_EXTENSION .o)
